name: CD Workflow

on:
  push:
    branches:
      production

jobs:
  build-project:
    name: Build project for publishing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Build project
        run: npm run build
