name: CI Workflow

on: 
  pull_request:
    branches:
      dev
      production

jobs:
  tests-and-checks:
    name: Run test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Run tests with jest
        run: npm run test
  
